baseURL = "https://pixelatedadventures.github.io/"
languageCode = "en-us"
title = "Pixelated Adventures"
theme = "hugo-creative-portfolio-theme"
enableRobotsTXT = true
# Enable comments by entering your Disqus shortname
disqusShortname = ""
# Enable Google Analytics by entering your tracking code
googleAnalytics = ""

[params]
  # Style options: default (pink), blue, green, pink, red, sea, violet
  # Use custom.css for your custom styling
  style = "violet"
  description = "A World of Fun at Your Fingertips"
  copyright = "&copy;2022 Pixelated Adventures"
  sidebarAbout = [
    "We are a small indie game studio from Madrid (Spain)",
    "We make games mainly with Unity and we also make assets for your store"
  ]
  # Contact page
     # Since this template is static, the contact form uses www.formspree.io as a
     # proxy. The form makes a POST request to their servers to send the actual
     # email. Visitors can send up to a 1000 emails each month for free.
     #
     # What you need to do for the setup?
     #
     # - set your email address under 'email' below
     # - upload the generated site to your server
     # - send a dummy email yourself to confirm your account
     # - click the confirm link in the email from www.formspree.io
     # - you're done. Happy mailing!
  email = "pixelatedadventures@outlook.com"

    # Optional Matomo analytics (formerly piwik)
      # [params.analytics.matomo]
      #  URL = "https://stats.example.com"
      #  ID = "42"
      #  # Track all subdomains with "*.example.com" (Optional)
      #  domain = "www.example.com"
      #  # Optional integrity check hash
      #  hash = ""

  # Nav links in the side bar
  [[params.navlinks]]
  name = "Home"
  url = "home/"
  home = true

  [[params.navlinks]]
  name = "The Team"
  url = "about/"

  [[params.navlinks]]
  name = "Get in touch"
  url = "contact/"
